name: DigitalNomadFamily
favicon: null
layout_spectrum: 0.7503884367179126
typography_spectrum: 0.560346003388986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.014975605066865683
  lightness: 0.04292569030076265
  saturation: 0.9053374186623842
  rhythmicContrast: 0.19234749185852706
purpose: []
